project:
  type: manuscript

execute:
  freeze: auto
  fig-width: 6
  fig-asp: 0.618
  message: false
  warning: false

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default



